"""
generate_turbsim_inputs.py — 生成"每间距一个盒"的 TurbSim .inp 文件。

背景（为什么需要按间距加宽盒子）
--------------------------------------------------------------------------
本工程用"风场旋转法"处理非零风向：把单列风机绕质心旋转 -offset，使入流沿 +X。
于是外侧风机的横向坐标随 offset×spacing 增大（Y-span = (n-1)*spacing*sin|offset|），
在 8D/±20° 可达 ±345 m（列展宽 5.47D）。此时 800 m 宽的通用盒**放不下**外侧
风机的转子高分辨率盒，FAST.Farm 运行期报：
    Grid4DField_GetVel: Outside the grid bounds ...
（正对风 offset=0 的工况 Y-span=0，800 盒够用，所以只有偏差工况失败。）

解决：为每个 (风速, TI, 间距) 生成一个**足够宽**的专用盒，命名带 _s{spacing}D，
create_ff_case / inflow_bts_for_case 会自动优先使用它。盒宽按该间距的最大偏差
(±20°) 计算，故同一间距的所有 offset 共用一个盒。

用法
--------------------------------------------------------------------------
    python -m induction_vs_yaw_study.turbsim_inp.generate_turbsim_inputs \
        --out ./FarmInputs

生成后，用 TurbSim 逐个跑这些 .inp 得到 .bts，放入工程的 FarmInputs 目录。
（TurbSim 需本地自备；生成 36 个盒可能耗时较长，可用附带的 run_all_turbsim.bat。）

参数依据（与前几轮一致，勿随意改动 HubHt/GridHeight）
--------------------------------------------------------------------------
  HubHt        = 175   （与工程既有可用盒一致；转子完整落在盒内）
  GridHeight   = 340
  NumGrid_Z    = 40
  AnalysisTime = 600   （单算例需 t_settle(360)+50*3=510s，留余量）
  RefHt        = 90    （NTM 参考高度）
  URef         = 风速  （6/8/10）
  IECturbc     = TI%   （5.0 / 10.0 / 15.0，对应 0.05/0.10/0.15）
  GridWidth / NumGrid_Y : 按间距自适应（见下），保证 dY_box <= 9.43（6m/s 约束）
"""
from __future__ import annotations

import argparse
import math
import os
from pathlib import Path

# ---- 扫描维度（与 grid 主配置保持一致）----
SPEEDS = [6.0, 8.0, 10.0]
TIS = [0.05, 0.10, 0.15]
SPACINGS_D = [2.0, 4.0, 6.0, 8.0]
MAX_ABS_OFFSET_DEG = 20.0          # 每间距盒按最大偏差取宽
N_TURBINES = 3
ROTOR_D = 126.0                    # NREL 5MW

# ---- 固定几何/时间参数 ----
HUB_HT = 175.0
GRID_HEIGHT = 340.0
NUMGRID_Z = 40
ANALYSIS_TIME = 600.0
USABLE_TIME = 600.0
REF_HT = 90.0
TIME_STEP = 0.05                   # TurbSim 内部步长；输出 10Hz 由 WrBLFF 决定
DT_OUT = 0.1                       # .bts 时间分辨率（匹配 DT_High=0.1）
DY_BOX_MAX = 9.43                  # 6 m/s 的 dY_Low_desired 上限


def required_gridwidth_m(spacing_D: float, offset_deg: float) -> float:
    """与 cases.required_gridwidth_m 同口径（此处独立实现以免耦合导入）。"""
    s_m = spacing_D * ROTOR_D
    xs = [i * s_m for i in range(N_TURBINES)]
    th = math.radians(-offset_deg)
    yr = [math.sin(th) * x for x in xs]
    ymean = sum(yr) / len(yr)
    yr = [y - ymean for y in yr]
    ymax = max(abs(y) for y in yr)
    span = max(yr) - min(yr)
    need_high = ymax + 1.0 * ROTOR_D          # 转子半跨 ~1D（含叶尖）
    need_low = span / 2.0 + 2.0 * ROTOR_D + 1.0 * ROTOR_D  # 走廊 2D + 蜿蜒 1D
    return 2.0 * max(need_high, need_low)


def box_params_for_spacing(spacing_D: float):
    """返回 (GridWidth, NumGrid_Y)，覆盖该间距全部 ±offset，且 dY_box<=9.43。"""
    w = required_gridwidth_m(spacing_D, MAX_ABS_OFFSET_DEG)
    grid_width = math.ceil(w / 20.0) * 20.0
    # NumGrid_Y 使 dY = W/(NY-1) <= 9.0（留余量到 9.43）
    ny = math.ceil(grid_width / 9.0) + 1
    dy = grid_width / (ny - 1)
    assert dy <= DY_BOX_MAX, f"dY={dy} > {DY_BOX_MAX} for s={spacing_D}"
    return grid_width, ny


TEMPLATE = """---------TurbSim v2.00.* Input File------------------------
3xNREL-5MW rotated-layout study inflow (generated by generate_turbsim_inputs.py).
---------Runtime Options-----------------------------------
False        Echo            - Echo input data to <RootName>.ech (flag)
{seed:d}   RandSeed1       - First random seed  (-2147483648 to 2147483647)
{seed2:d}   RandSeed2       - Second random seed (-2147483648 to 2147483647) for intrinsic pRNG, or an alternative pRNG: "RanLux" or "RNSNLW"
False        WrBHHTP         - Output hub-height turbulence parameters in binary form?  (Generates RootName.bin)
False        WrFHHTP         - Output hub-height turbulence parameters in formatted form?  (Generates RootName.dat)
False        WrADHH          - Output hub-height time-series data in AeroDyn form?  (Generates RootName.hh)
True         WrADFF          - Output full-field time-series data in TurbSim/AeroDyn form? (Generates RootName.bts)
False        WrBLFF          - Output full-field time-series data in BLADED/AeroDyn form?  (Generates RootName.wnd)
False        WrADTWR         - Output tower time-series data? (Generates RootName.twr)
False        WrFMTFF         - Output full-field time-series data in formatted (readable) form?  (Generates RootName.u, RootName.v, RootName.w)
False        WrACT           - Output coherent turbulence time steps in AeroDyn form? (Generates RootName.cts)
True         Clockwise       - Clockwise rotation looking downwind? (used only for full-field binary files - not necessary for AeroDyn)
         1   ScaleIEC        - Scale IEC turbulence models to exact target standard deviation? [0=no additional scaling; 1=use hub scale uniformly; 2=use individual scales]

--------Turbine/Model Specifications-----------------------
       {numgrid_z:d}   NumGrid_Z       - Vertical grid-point matrix dimension
      {numgrid_y:d}   NumGrid_Y       - Horizontal grid-point matrix dimension
      {time_step:.4g}   TimeStep        - Time step [seconds]
    {analysis_time:.1f}   AnalysisTime    - Length of analysis time series [seconds] (program will add time if necessary: AnalysisTime = MAX(AnalysisTime, UsableTime+GridWidth/MeanHHWS) )
    "ALL"   UsableTime      - Usable length of output time series [seconds] (program will add GridWidth/MeanHHWS seconds unless UsableTime is "ALL")
      {hub_ht:g}   HubHt           - Hub height [m] (should be > 0.5*GridHeight)
      {grid_height:g}   GridHeight      - Grid height [m]
     {grid_width:g}   GridWidth       - Grid width [m] (should be >= 2*(RotorRadius+ShaftLength))
        0   VFlowAng        - Vertical mean flow (uptilt) angle [degrees]
        0   HFlowAng        - Horizontal mean flow (skew) angle [degrees]

--------Meteorological Boundary Conditions-------------------
"IECKAI"    TurbModel       - Turbulence model ("IECKAI","IECVKM","GP_LLJ","NWTCUP","SMOOTH","WF_UPW","WF_07D","WF_14D","TIDAL","API","USRINP","TIMESR", or "NONE")
"None"      UserFile        - Name of the file that contains inputs for user-defined spectra or time series inputs (used only for "USRINP" and "TIMESR" models)
        1   IECstandard     - Number of IEC 61400-x standard (x=1,2, or 3 with optional 61400.1 edition number (i.e. "1-Ed2") )
"{iecturbc:.1f}"      IECturbc        - IEC turbulence characteristic ("A", "B", "C" or the turbulence intensity in percent) ("KHTEST" option with NWTCUP model, not used for other models)
"NTM"       IEC_WindType    - IEC turbulence type ("NTM"=normal, "xETM"=extreme turbulence, "xEWM1"=extreme 1-year wind, "xEWM50"=extreme 50-year wind, where x=wind turbine class 1, 2, or 3)
"default"   ETMc            - IEC Extreme Turbulence Model "c" parameter [m/s]
"PL"        WindProfileType - Velocity profile type ("LOG";"PL"=power law;"JET";"H2L"=Log law for TIDAL model;"API";"USR";"TS";"IEC"=PL on rotor disk, LOG elsewhere; or "default")
"None"      ProfileFile     - Name of the file that contains input profiles for WindProfileType="USR" and/or TurbModel="USRVKM" [-]
     {ref_ht:g}   RefHt           - Height of the reference velocity (URef) [m]
      {uref:g}   URef            - Mean (total) velocity at the reference height [m/s] (or "default" for JET velocity profile) [must be 1-hr mean for API model; otherwise is the mean over AnalysisTime seconds]
      350   ZJetMax         - Jet height [m] (used only for JET velocity profile, valid 70-490 m)
"0.2"       PLExp           - Power law exponent [-] (or "default")
"default"   Z0              - Surface roughness length [m] (or "default")

--------Non-IEC Meteorological Boundary Conditions------------
"default"   Latitude        - Site latitude [degrees] (or "default")
     0.05   RICH_NO         - Gradient Richardson number [-]
"default"   UStar           - Friction or shear velocity [m/s] (or "default")
"default"   ZI              - Mixing layer depth [m] (or "default")
"default"   PC_UW           - Hub mean u'w' Reynolds stress [m^2/s^2] (or "default" or "none")
"default"   PC_UV           - Hub mean u'v' Reynolds stress [m^2/s^2] (or "default" or "none")
"default"   PC_VW           - Hub mean v'w' Reynolds stress [m^2/s^2] (or "default" or "none")

--------Spatial Coherence Parameters----------------------------
"IEC"       SCMod1           - u-component coherence model ("GENERAL","IEC","API","NONE", or "default")
"IEC"       SCMod2           - v-component coherence model ("GENERAL","IEC","NONE", or "default")
"IEC"       SCMod3           - w-component coherence model ("GENERAL","IEC","NONE", or "default")
"12.0 0.00035273"     InCDec1          - u-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
"12.0 0.00035273"     InCDec2          - v-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
"12.0 0.00035273"     InCDec3          - w-component coherence parameters for general or IEC models [-, m^-1] (e.g. "10.0  0.3e-3" in quotes) (or "default")
0.0         CohExp           - Coherence exponent for general model [-] (or "default")

--------Coherent Turbulence Scaling Parameters-------------------
".\\EventData"    CTEventPath     - Name of the path where event data files are located
"random"      CTEventFile     - Type of event files ("LES", "DNS", or "RANDOM")
true          Randomize       - Randomize the disturbance scale and locations? (true/false)
          1   DistScl         - Disturbance scale [-] (ratio of event dataset height to rotor disk). (Ignored when Randomize = true.)
        0.5   CTLy            - Fractional location of tower centerline from right [-] (looking downwind) to left side of the dataset. (Ignored when Randomize = true.)
        0.5   CTLz            - Fractional location of hub height from the bottom of the dataset. [-] (Ignored when Randomize = true.)
         30   CTStartTime     - Minimum start time for coherent structures in RootName.cts [seconds]

====================================================
! NOTE: Do not add or remove any lines in this file!
====================================================
"""


def ti_to_iecturbc(ti: float) -> float:
    return round(ti * 100.0, 1)


def fname(speed: float, ti: float, spacing_D: float) -> str:
    s = int(round(speed))
    t = int(round(ti * 100))
    return f"inflow_{s:02d}ms_TI{t:02d}_s{spacing_D:g}D.inp"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="./FarmInputs",
                    help="输出 .inp 目录")
    ap.add_argument("--seed", type=int, default=123456,
                    help="RandSeed1 起始值（逐盒 +1，保证各盒不同实现）")
    ap.add_argument("--generic", action="store_true",
                    help="只生成 9 个**通用盒**（inflow_06ms_TI05.bts，无 _sXD 后缀），"
                         "宽度按 offset=0 取（~760m）。适合当前 grid 只有 wd=0 的情况，"
                         "更省时省盘。工程会自动回退使用这些通用盒。")
    args = ap.parse_args()

    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    # ---- 通用盒模式：9 个 (风速×TI)，宽度按 offset=0（列在 X 轴，ycoords=0）----
    if args.generic:
        w0 = required_gridwidth_m(2.0, 0.0)          # offset=0 时各间距相同
        grid_width = math.ceil(w0 / 20.0) * 20.0
        ny = math.ceil(grid_width / 9.0) + 1
        dy = grid_width / (ny - 1)
        print(f"通用盒（wd=0）：GridWidth={grid_width:.0f} m, NumGrid_Y={ny}, "
              f"dY={dy:.2f} m（<=9.43 ✓），共 {len(SPEEDS)*len(TIS)} 个\n")
        n = 0
        seed = args.seed
        for speed in SPEEDS:
            for ti in TIS:
                txt = TEMPLATE.format(
                    seed=seed, seed2=seed + 1000000, numgrid_z=NUMGRID_Z, numgrid_y=ny,
                    time_step=TIME_STEP, analysis_time=ANALYSIS_TIME,
                    usable_time=USABLE_TIME, hub_ht=HUB_HT,
                    grid_height=GRID_HEIGHT, grid_width=grid_width,
                    iecturbc=ti_to_iecturbc(ti), ref_ht=REF_HT, uref=speed,
                )
                s = int(round(speed)); t = int(round(ti * 100))
                (out / f"inflow_{s:02d}ms_TI{t:02d}.inp").write_text(txt)
                seed += 1
                n += 1
        print(f"已生成 {n} 个通用盒 .inp 到 {out.resolve()}")
        print("命名形如 inflow_06ms_TI05.inp；跑 TurbSim 得同名 .bts 放入 FarmInputs。")
        print("注意：这些盒**仅适用 wd=0**；要跑 ±偏差工况需改用 per-spacing 盒（去掉 --generic）。")
        return

    # 预览每间距的盒参数
    print("每间距盒参数（覆盖该间距全部 ±offset）：")
    per_spacing = {}
    for sp in SPACINGS_D:
        gw, ny = box_params_for_spacing(sp)
        per_spacing[sp] = (gw, ny)
        dy = gw / (ny - 1)
        print(f"  s={sp:g}D: GridWidth={gw:.0f} m, NumGrid_Y={ny}, dY={dy:.2f} m")
    print()

    n = 0
    seed = args.seed
    for sp in SPACINGS_D:
        gw, ny = per_spacing[sp]
        for speed in SPEEDS:
            for ti in TIS:
                txt = TEMPLATE.format(
                    seed=seed,
                    seed2=seed + 1000000,
                    numgrid_z=NUMGRID_Z,
                    numgrid_y=ny,
                    time_step=TIME_STEP,
                    analysis_time=ANALYSIS_TIME,
                    usable_time=USABLE_TIME,
                    hub_ht=HUB_HT,
                    grid_height=GRID_HEIGHT,
                    grid_width=gw,
                    iecturbc=ti_to_iecturbc(ti),
                    ref_ht=REF_HT,
                    uref=speed,
                )
                p = out / fname(speed, ti, sp)
                p.write_text(txt)
                seed += 1
                n += 1
    print(f"已生成 {n} 个 .inp 到 {out.resolve()}")
    print("命名形如 inflow_06ms_TI05_s8D.inp；跑 TurbSim 得到同名 .bts 后放入 FarmInputs。")
    print("工程会对每个工况优先使用 _s{spacing}D 专用盒（找不到才回退通用盒）。")


if __name__ == "__main__":
    main()
